### ISSUE TITLE
GLIBC 2.27 not available

### ISSUE THREAD

**Issue by jianshu93** [hsadasivan/mm2-ax#1]
Dear mm2-ax team,

I found that the provided binary is not compatible with old version of Linux operation system such as RHEL 7.8 and Ubuntu 16, centOS 6, which a majority of the supercomputer are now using. Can you please also proved a binary built on such systems.

Thanks,

Jianshu

**Comment by harisankarsadasivan** [comment]
Dear @jianshu93

Thank You for your interest.
OS versions requested seem to be unavailable on GCP. I'm guessing it's because they have reached end of free support period.
Currently, we only support the mentioned hardware configuration on GCP. 

-Hari
