### ISSUE TITLE
nvlink?

### ISSUE THREAD

**Issue by nmb85** [hsadasivan/mm2-ax#2]
Hi, could this be run on two RTX 3090 with nvlink and 48G of pooled memory instead of an A100?

**Comment by harisankarsadasivan** [comment]
Hello, 
Unfortunately, not out of the box.
Please email msamadi@nvidia.com.

**Comment by jamesdalg** [comment]
@nmb85 If you find a way to do this, feel free to share. I've a similar problem with my pair of A5000s. Parabricks runs with 4 GPUs as a recommended configuration and it's incredibly effective, turning 36-48 hours into ~3 hours. It's wonderful. I thoroughly think everyone in the community would find this helpful, especially those who use AWS.
