### ISSUE TITLE
Floating point exception - WSL2 Nvidia RTX A2000 6GB

### ISSUE THREAD

**Issue by husamia** [hsadasivan/mm2-ax#3]
I am getting the error when running it using WSL2

here are the details on my GPU and OS

```
~$ ~/mm2-ax/bin/mm2-ax
Floating point exception
~$ uname -a
Linux microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
~$nvidia-smi
Wed Apr 19 16:53:59 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.75       Driver Version: 517.37       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A2000    On   | 00000000:B3:00.0  On |                  Off |
| 30%   35C    P8    11W /  70W |   3442MiB /  6138MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        22      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+
```

**Comment by N-damo** [comment]
> I am getting the error when running it using WSL2
> 
> here are the details on my GPU and OS
> 
> ```
> ~$ ~/mm2-ax/bin/mm2-ax
> Floating point exception
> ~$ uname -a
> Linux microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> ~$nvidia-smi
> Wed Apr 19 16:53:59 2023
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 515.75       Driver Version: 517.37       CUDA Version: 11.7     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA RTX A2000    On   | 00000000:B3:00.0  On |                  Off |
> | 30%   35C    P8    11W /  70W |   3442MiB /  6138MiB |      1%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A        22      G   /Xwayland                       N/A      |
> +-----------------------------------------------------------------------------+
> ```
use whole command ,not only `bin/mm2-ax`:
`bin/mm2-ax -t 1 -x map-ont hg38.mmi ip.fa --total-no-of-reads=1 --blocks-per-stream=9  `

**Comment by harisankarsadasivan** [comment]
NVIDIA has a solution here: https://docs.nvidia.com/clara/parabricks/latest/documentation/tooldocs/man_minimap2.html
AMD has a solution here: https://github.com/Minimap2onGPU/mm2-gb
