### ISSUE TITLE
Is this a tech demo or intended for actual use ?

### ISSUE THREAD

**Issue by colindaven** [hsadasivan/mm2-ax#4]
Hi,

this all sounds great until you get to the limitations. The whole point of the tool is to speed up minimap2, yet end to end speedup has not been optimized. That's quite a large contradiction.

So is this intended to be used one day, and will it be further developed, or is it just a tech demo for a paper ?

There is a real need for a more efficient long read aligner.

Thanks
Colin

**Comment by jamesdalg** [comment]
Better to use the official NVIDIA version: https://docs.nvidia.com/clara/parabricks/latest/documentation/tooldocs/man_minimap2.html#man-minimap2 This site hasn't been updated.
